#!/bin/bash

#SBATCH --job-name=large-2000_02a_read_sim_and_qc
#SBATCH --partition=jrw0107_std
#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 20:00:00
#SBATCH --mem=4000
#SBATCH --mail-type=end,fail
#SBATCH --mail-user=avrilharder@gmail.com


# -----------------------------------------------------------------------------
# Set variables for this step
# -----------------------------------------------------------------------------

STEP=02_read_sim_and_qc
PREV_STEP=01_slim
SCRIPT=02a_run_art.sh

# -----------------------------------------------------------------------------
# Load variables and functions from settings file
# -----------------------------------------------------------------------------

source /home/amh0254/roh_param_project/roh_inference_testing/simulated/bash/99_includes/init_script_vars.sh

# -----------------------------------------------------------------------------
# Load modules
# -----------------------------------------------------------------------------

module load artmountrainier/2016.06.05

# -----------------------------------------------------------------------------
# Run read simulation
#
# INPUT_DIR, SLIM_OUT_DIR, FASTA_OUT_DIR, OUTPUT_DIR, and SAMPLE_ID_LIST are
# set in  init_script_vars.sh
# -----------------------------------------------------------------------------

# Starting with 50X coverage for now (25X per haploid genome, i.e., FASTA file)
# Will downsample unfiltered BAM files generated by BWA.
# 150-bp paired-end reads (--len and --paired parameters).
# Using the HiSeq 2500 error model (--seqSys parameter).

# for d in ${dems[@]}; do

	VCF_OUT_DIR=${INIT_OUTPUT_DIR}/sample_vcf_files_large-2000
	FASTA_OUT_DIR=${INIT_OUTPUT_DIR}/sample_fasta_files_large-2000
	SAMPLE_ID_LIST=${INIT_OUTPUT_DIR}/sample_ID_list_large-2000.txt

	while read -a line; do

		if [ ! -f ${OUTPUT_DIR}/large-2000_${line[0]}_11.fq ]
		then

			for a in 1 2; do
		
				start_logging "ART Read - ${line[0]}_$a.fasta"
			
				art_illumina \
					--seqSys HS25 \
					-i ${FASTA_OUT_DIR}/large-2000_${line[0]}_$a.fasta \
					--paired \
					-na \
					--len 150 \
					--fcov 25 \
					-m 500 \
					-s 75 \
					-o ${OUTPUT_DIR}/large-2000_${line[0]}_$a

				# echo ${FASTA_OUT_DIR}/${line[0]}_$a.fas
				# echo ${OUTPUT_DIR}/${line[0]}_$a

				stop_logging
			
			done
			
		fi

	done < ${SAMPLE_ID_LIST}

# done

# mail -s 'ART run finished' avrilharder@gmail.com <<<'SLiM run finished'

# -----------------------------------------------------------------------------
# Copy output files to user's home directory.
# -----------------------------------------------------------------------------

# source /home/amh0254/roh_param_project/roh_inference_testing/simulated/bash/99_includes/backup_output.sh
